name: NodeJS with Grunt

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: prepare screeps auth
      run: |
        echo "{ \"email\": \"${{ secrets.SCREEPS_EMAIL }}\", \"token\": \"${{ secrets.SCREEPS_TOKEN }}\" }" > screeps.auth.secret
    
    - name: Build
      run: |
        npm install
        
        branch=:${{ github.ref_name }}
        if [ ${{ github.ref_name }} == "main" ]
        then
          branch=
        fi
        
        grunt --stack verbose deploy$branch

    - name: cleanup secrets
      run: |
        rm -f ./*.secret
    
